version: "3.9"

services:
  app:
    container_name: app-nrich
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ../src/:/app

  web:
    container_name: web-nrich
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ../src/:/app

  db:
    container_name: db-nrich
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume-nrich:/var/lib/mysql

  mail:
    container_name: mail-nrich
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  phpmyadmin:
    container_name: phpmyadmin-nrich
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=laravel
      - PMA_PASSWORD=password
    ports:
      - 3000:80

volumes:
  mysql-volume-nrich:
